// Code generated by protoc-gen-go. DO NOT EDIT.
// source: marlin/protocols/tmDataTransferProtocolv1/tendermintMessage.proto

package tmDataTransferProtocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PacketMsg struct {
	Eof                  uint32   `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	DataBytes            []byte   `protobuf:"bytes,3,opt,name=dataBytes,proto3" json:"dataBytes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PacketMsg) Reset()         { *m = PacketMsg{} }
func (m *PacketMsg) String() string { return proto.CompactTextString(m) }
func (*PacketMsg) ProtoMessage()    {}
func (*PacketMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a5a70136d1ab93, []int{0}
}

func (m *PacketMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PacketMsg.Unmarshal(m, b)
}
func (m *PacketMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PacketMsg.Marshal(b, m, deterministic)
}
func (m *PacketMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PacketMsg.Merge(m, src)
}
func (m *PacketMsg) XXX_Size() int {
	return xxx_messageInfo_PacketMsg.Size(m)
}
func (m *PacketMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_PacketMsg.DiscardUnknown(m)
}

var xxx_messageInfo_PacketMsg proto.InternalMessageInfo

func (m *PacketMsg) GetEof() uint32 {
	if m != nil {
		return m.Eof
	}
	return 0
}

func (m *PacketMsg) GetDataBytes() []byte {
	if m != nil {
		return m.DataBytes
	}
	return nil
}

type TendermintMessage struct {
	ChainId              uint32       `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Channel              uint32       `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Packets              []*PacketMsg `protobuf:"bytes,3,rep,name=packets,proto3" json:"packets,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *TendermintMessage) Reset()         { *m = TendermintMessage{} }
func (m *TendermintMessage) String() string { return proto.CompactTextString(m) }
func (*TendermintMessage) ProtoMessage()    {}
func (*TendermintMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c8a5a70136d1ab93, []int{1}
}

func (m *TendermintMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TendermintMessage.Unmarshal(m, b)
}
func (m *TendermintMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TendermintMessage.Marshal(b, m, deterministic)
}
func (m *TendermintMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TendermintMessage.Merge(m, src)
}
func (m *TendermintMessage) XXX_Size() int {
	return xxx_messageInfo_TendermintMessage.Size(m)
}
func (m *TendermintMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TendermintMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TendermintMessage proto.InternalMessageInfo

func (m *TendermintMessage) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *TendermintMessage) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *TendermintMessage) GetPackets() []*PacketMsg {
	if m != nil {
		return m.Packets
	}
	return nil
}

func init() {
	proto.RegisterType((*PacketMsg)(nil), "tmDataTransferProtocol.PacketMsg")
	proto.RegisterType((*TendermintMessage)(nil), "tmDataTransferProtocol.TendermintMessage")
}

func init() {
	proto.RegisterFile("marlin/protocols/tmDataTransferProtocolv1/tendermintMessage.proto", fileDescriptor_c8a5a70136d1ab93)
}

var fileDescriptor_c8a5a70136d1ab93 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x72, 0xcc, 0x4d, 0x2c, 0xca,
	0xc9, 0xcc, 0xd3, 0x2f, 0x28, 0xca, 0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0x29, 0xd6, 0x2f, 0xc9, 0x75,
	0x49, 0x2c, 0x49, 0x0c, 0x29, 0x4a, 0xcc, 0x2b, 0x4e, 0x4b, 0x2d, 0x0a, 0x80, 0x8a, 0x97, 0x19,
	0xea, 0x97, 0xa4, 0xe6, 0xa5, 0xa4, 0x16, 0xe5, 0x66, 0xe6, 0x95, 0xf8, 0xa6, 0x16, 0x17, 0x27,
	0xa6, 0xa7, 0xea, 0x81, 0x35, 0x09, 0x89, 0x61, 0xd7, 0xa1, 0x64, 0xcd, 0xc5, 0x19, 0x90, 0x98,
	0x9c, 0x9d, 0x5a, 0xe2, 0x5b, 0x9c, 0x2e, 0x24, 0xc0, 0xc5, 0x9c, 0x9a, 0x9f, 0x26, 0xc1, 0xa4,
	0xc0, 0xa8, 0xc1, 0x1b, 0x04, 0x62, 0x0a, 0xc9, 0x70, 0x71, 0xa6, 0x00, 0xb5, 0x39, 0x55, 0x96,
	0xa4, 0x16, 0x4b, 0x30, 0x03, 0xc5, 0x79, 0x82, 0x10, 0x02, 0x4a, 0x2d, 0x8c, 0x5c, 0x82, 0x21,
	0xe8, 0x16, 0x0a, 0x49, 0x70, 0xb1, 0x27, 0x67, 0x24, 0x66, 0xe6, 0x79, 0xa6, 0x48, 0x30, 0x82,
	0x4d, 0x82, 0x71, 0xa1, 0x32, 0x79, 0x79, 0xa9, 0x39, 0x50, 0x3b, 0x60, 0x5c, 0x21, 0x6b, 0x2e,
	0xf6, 0x02, 0xb0, 0x33, 0x40, 0xb6, 0x30, 0x6b, 0x70, 0x1b, 0x29, 0xea, 0x61, 0x77, 0xb0, 0x1e,
	0xdc, 0xb5, 0x41, 0x30, 0x1d, 0x49, 0x6c, 0x60, 0x2f, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xbb, 0x44, 0x3c, 0x40, 0x27, 0x01, 0x00, 0x00,
}
