// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tendermintMessage.proto

package tmDataTransferProtocol

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TendermintMessage struct {
	ChainId              uint32   `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Channel              uint32   `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TendermintMessage) Reset()         { *m = TendermintMessage{} }
func (m *TendermintMessage) String() string { return proto.CompactTextString(m) }
func (*TendermintMessage) ProtoMessage()    {}
func (*TendermintMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_24437a978e595261, []int{0}
}

func (m *TendermintMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TendermintMessage.Unmarshal(m, b)
}
func (m *TendermintMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TendermintMessage.Marshal(b, m, deterministic)
}
func (m *TendermintMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TendermintMessage.Merge(m, src)
}
func (m *TendermintMessage) XXX_Size() int {
	return xxx_messageInfo_TendermintMessage.Size(m)
}
func (m *TendermintMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_TendermintMessage.DiscardUnknown(m)
}

var xxx_messageInfo_TendermintMessage proto.InternalMessageInfo

func (m *TendermintMessage) GetChainId() uint32 {
	if m != nil {
		return m.ChainId
	}
	return 0
}

func (m *TendermintMessage) GetChannel() uint32 {
	if m != nil {
		return m.Channel
	}
	return 0
}

func (m *TendermintMessage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*TendermintMessage)(nil), "tmDataTransferProtocol.TendermintMessage")
}

func init() {
	proto.RegisterFile("tendermintMessage.proto", fileDescriptor_24437a978e595261)
}

var fileDescriptor_24437a978e595261 = []byte{
	// 129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2f, 0x49, 0xcd, 0x4b,
	0x49, 0x2d, 0xca, 0xcd, 0xcc, 0x2b, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x12, 0x2b, 0xc9, 0x75, 0x49, 0x2c, 0x49, 0x0c, 0x29, 0x4a, 0xcc, 0x2b,
	0x4e, 0x4b, 0x2d, 0x0a, 0x00, 0x09, 0x26, 0xe7, 0xe7, 0x28, 0x45, 0x73, 0x09, 0x86, 0xa0, 0x6b,
	0x11, 0x92, 0xe0, 0x62, 0x4f, 0xce, 0x48, 0xcc, 0xcc, 0xf3, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0d, 0x82, 0x71, 0xa1, 0x32, 0x79, 0x79, 0xa9, 0x39, 0x12, 0x4c, 0x70, 0x19, 0x10, 0x57,
	0x48, 0x88, 0x8b, 0x25, 0x05, 0x68, 0x81, 0x04, 0x33, 0x50, 0x98, 0x27, 0x08, 0xcc, 0x4e, 0x62,
	0x03, 0xdb, 0x6d, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x2d, 0x61, 0x90, 0x96, 0x00, 0x00,
	0x00,
}
