// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: protocols/tmDataTransferProtocolv1/tendermintMessage.proto

package tmDataTransferProtocol

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type PacketMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Eof       uint32 `protobuf:"varint,2,opt,name=eof,proto3" json:"eof,omitempty"`
	DataBytes []byte `protobuf:"bytes,3,opt,name=dataBytes,proto3" json:"dataBytes,omitempty"`
}

func (x *PacketMsg) Reset() {
	*x = PacketMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PacketMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PacketMsg) ProtoMessage() {}

func (x *PacketMsg) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PacketMsg.ProtoReflect.Descriptor instead.
func (*PacketMsg) Descriptor() ([]byte, []int) {
	return file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_rawDescGZIP(), []int{0}
}

func (x *PacketMsg) GetEof() uint32 {
	if x != nil {
		return x.Eof
	}
	return 0
}

func (x *PacketMsg) GetDataBytes() []byte {
	if x != nil {
		return x.DataBytes
	}
	return nil
}

type TendermintMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChainId uint32       `protobuf:"varint,1,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Channel uint32       `protobuf:"varint,2,opt,name=channel,proto3" json:"channel,omitempty"`
	Packets []*PacketMsg `protobuf:"bytes,3,rep,name=packets,proto3" json:"packets,omitempty"`
}

func (x *TendermintMessage) Reset() {
	*x = TendermintMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TendermintMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TendermintMessage) ProtoMessage() {}

func (x *TendermintMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TendermintMessage.ProtoReflect.Descriptor instead.
func (*TendermintMessage) Descriptor() ([]byte, []int) {
	return file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_rawDescGZIP(), []int{1}
}

func (x *TendermintMessage) GetChainId() uint32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *TendermintMessage) GetChannel() uint32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *TendermintMessage) GetPackets() []*PacketMsg {
	if x != nil {
		return x.Packets
	}
	return nil
}

var File_protocols_tmDataTransferProtocolv1_tendermintMessage_proto protoreflect.FileDescriptor

var file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_rawDesc = []byte{
	0x0a, 0x3a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x74, 0x6d, 0x44, 0x61,
	0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x76, 0x31, 0x2f, 0x74, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x16, 0x74, 0x6d,
	0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x3b, 0x0a, 0x09, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x73,
	0x67, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6f, 0x66, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03,
	0x65, 0x6f, 0x66, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x61, 0x74, 0x61, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x64, 0x61, 0x74, 0x61, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x22, 0x84, 0x01, 0x0a, 0x11, 0x54, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x3b, 0x0a, 0x07, 0x70,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x74,
	0x6d, 0x44, 0x61, 0x74, 0x61, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x50, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x4d, 0x73, 0x67, 0x52,
	0x07, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_rawDescOnce sync.Once
	file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_rawDescData = file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_rawDesc
)

func file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_rawDescGZIP() []byte {
	file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_rawDescOnce.Do(func() {
		file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_rawDescData)
	})
	return file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_rawDescData
}

var file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_goTypes = []interface{}{
	(*PacketMsg)(nil),         // 0: tmDataTransferProtocol.PacketMsg
	(*TendermintMessage)(nil), // 1: tmDataTransferProtocol.TendermintMessage
}
var file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_depIdxs = []int32{
	0, // 0: tmDataTransferProtocol.TendermintMessage.packets:type_name -> tmDataTransferProtocol.PacketMsg
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_init() }
func file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_init() {
	if File_protocols_tmDataTransferProtocolv1_tendermintMessage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PacketMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TendermintMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_goTypes,
		DependencyIndexes: file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_depIdxs,
		MessageInfos:      file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_msgTypes,
	}.Build()
	File_protocols_tmDataTransferProtocolv1_tendermintMessage_proto = out.File
	file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_rawDesc = nil
	file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_goTypes = nil
	file_protocols_tmDataTransferProtocolv1_tendermintMessage_proto_depIdxs = nil
}
